name: Run test jobs
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: plus3it/actions-workflows/.github/workflows/test.yml@7a39c78aa90050c7d705f28fe93d18ae139cdc05
